import { describe, expect, it } from "vitest";
import { isWatcherError, type WatcherError } from "@/lib/watcher/errors";
import {
  normalizeWebsiteContent,
  normalizeWhitespace,
} from "@/lib/watcher/normalize";

/**
 * What a page reduces to, and what it takes to change it.
 *
 * Every test here is one half of the same question: **markup churn must not
 * move the text, and a word the reader can see must.** The first half is what
 * makes a watcher worth having — a page that reports a change every morning
 * because its build hashed the class names differently is a page nobody will
 * keep watching. The second half is the feature.
 */

/** The text a page reduces to. */
function textOf(html: string): string {
  return normalizeWebsiteContent(html, "text/html").normalizedContent;
}

/** The digest a page reduces to. */
function hashOf(html: string): string {
  return normalizeWebsiteContent(html, "text/html").contentHash;
}

function page(body: string, head = ""): string {
  return `<!DOCTYPE html><html><head>${head}</head><body>${body}</body></html>`;
}

describe("the text a document reduces to", () => {
  it("is the words, in the order they are written", () => {
    expect(textOf(page("<h1>Careers</h1><p>We are hiring.</p>"))).toBe(
      "Careers We are hiring.",
    );
  });

  it("includes the title, which is shown to the reader", () => {
    expect(textOf(page("<p>Body</p>", "<title>Careers</title>"))).toBe(
      "Careers Body",
    );
  });

  it("changes when the title changes", () => {
    const before = hashOf(page("<p>Body</p>", "<title>採用情報</title>"));
    const after = hashOf(page("<p>Body</p>", "<title>2027年度 採用情報</title>"));

    expect(after).not.toBe(before);
  });

  /**
   * Metadata is written for other machines and revised on its own schedule —
   * a deploy stamp in a canonical URL, a description regenerated by a CMS.
   * Watching it would report changes nobody made.
   */
  it("leaves the rest of the head out", () => {
    const head = `
      <title>Careers</title>
      <meta name="description" content="a description nobody sees">
      <meta property="og:title" content="an open graph title">
      <link rel="canonical" href="https://example.com/careers?v=93">
      <script type="application/ld+json">{"@type":"JobPosting"}</script>
    `;

    expect(textOf(page("<p>Body</p>", head))).toBe("Careers Body");
  });
});

describe("what is not part of the document", () => {
  it.each([
    ["script", "<script>const requestId = 'a91f';</script>"],
    ["style", "<style>.a{color:red}</style>"],
    ["noscript", "<noscript>Turn on JavaScript</noscript>"],
    ["template", "<template><p>not shown yet</p></template>"],
    ["svg", "<svg><title>icon</title><text>drawn</text></svg>"],
    ["canvas", "<canvas>fallback</canvas>"],
    ["iframe", "<iframe><p>someone else's page</p></iframe>"],
  ])("drops %s and everything inside it", (_tag, markup) => {
    expect(textOf(page(`<p>Before</p>${markup}<p>After</p>`))).toBe(
      "Before After",
    );
  });

  /**
   * The one attribute that is honoured, and it is honoured because it is not
   * styling: `hidden` is HTML saying the element is not currently relevant.
   */
  it("drops a hidden element and its descendants", () => {
    expect(
      textOf(page("<p>Shown</p><div hidden><p>secret</p></div>")),
    ).toBe("Shown");
  });

  it.each(['hidden=""', 'hidden="hidden"', 'hidden="false"'])(
    "treats %s as hidden, because presence is what a boolean attribute means",
    (attribute) => {
      expect(textOf(page(`<p>Shown</p><div ${attribute}>secret</div>`))).toBe(
        "Shown",
      );
    },
  );
});

/**
 * **`aria-hidden` describes what a screen reader should skip**, which is
 * routinely not what is invisible: decorative duplicates carry it, and so does
 * plenty of text that is very much on the page. Honouring it would drop
 * content on the strength of a guess about rendering.
 */
describe("what looks hidden but is kept", () => {
  it('keeps text marked aria-hidden="true"', () => {
    expect(textOf(page('<p>Shown</p><p aria-hidden="true">Also shown</p>'))).toBe(
      "Shown Also shown",
    );
  });

  /**
   * Reading `display:none` from an attribute while ignoring the style sheet
   * that sets the same rule on a class would treat two identical pages
   * differently depending on where their authors put the rule.
   */
  it("keeps text hidden by inline style, which it does not interpret", () => {
    expect(
      textOf(page('<p>Shown</p><p style="display:none">Also shown</p>')),
    ).toBe("Shown Also shown");
  });
});

/**
 * These are removed by plenty of readability tools, and removing them here
 * would throw away exactly what many people watch a page for: an opening hour
 * in a footer, a notice in a header, a new item in a nav.
 */
describe("landmarks that are kept", () => {
  it.each([
    "header",
    "nav",
    "main",
    "article",
    "aside",
    "section",
    "footer",
  ])("keeps the contents of %s", (tag) => {
    expect(textOf(page(`<${tag}>Words</${tag}>`))).toBe("Words");
  });
});

describe("markup churn that must not move the text", () => {
  const withAttributes = page(
    '<div class="a-1f9" id="root-1" data-request-id="111" data-testid="x"' +
      ' style="color:red" onclick="track(1)">Hello</div>',
  );
  const withOtherAttributes = page(
    '<div class="b-77c" id="root-2" data-request-id="222" data-testid="y"' +
      ' style="color:blue" onclick="track(2)">Hello</div>',
  );

  it("ignores attributes entirely", () => {
    expect(textOf(withAttributes)).toBe("Hello");
    expect(hashOf(withOtherAttributes)).toBe(hashOf(withAttributes));
  });

  it("ignores how an entity was spelled", () => {
    expect(hashOf(page("<p>A &amp; B</p>"))).toBe(hashOf(page("<p>A & B</p>")));
    expect(textOf(page("<p>A &amp; B</p>"))).toBe("A & B");
  });

  it.each([
    ["&#38;", "&"],
    ["&lt;", "<"],
    ["&gt;", ">"],
    ["&quot;", '"'],
    ["&#x3042;", "あ"],
  ])("decodes %s to %s", (entity, decoded) => {
    expect(textOf(page(`<p>${entity}</p>`))).toBe(decoded);
  });

  it.each([
    ["multiple spaces", "<p>A     B</p>"],
    ["a newline", "<p>A\nB</p>"],
    ["a tab", "<p>A\tB</p>"],
    ["mixed whitespace", "<p>A \t\n \r B</p>"],
    ["a non-breaking space", "<p>A&nbsp;B</p>"],
    ["an ideographic space", "<p>A　B</p>"],
    ["an en space", "<p>A B</p>"],
  ])("collapses %s", (_name, markup) => {
    expect(textOf(page(markup))).toBe("A B");
  });

  it("trims the ends", () => {
    expect(textOf(page("<p>   \n  Hello  \n   </p>"))).toBe("Hello");
  });

  it("is unmoved by reindenting the markup", () => {
    const minified = page("<div><p>One</p><p>Two</p></div>");
    const pretty = page(`
      <div>
        <p>One</p>
        <p>Two</p>
      </div>
    `);

    expect(hashOf(pretty)).toBe(hashOf(minified));
  });
});

describe("where words are joined and where they are separated", () => {
  /**
   * Two spans are one line of text. Inserting a space would be inventing
   * whitespace the page does not have.
   */
  it("does not invent a space between inline elements", () => {
    expect(textOf(page("<span>A</span><span>B</span>"))).toBe("AB");
  });

  it("keeps a space the markup actually contains", () => {
    expect(textOf(page("<span>A</span> <span>B</span>"))).toBe("A B");
  });

  /** Running two paragraphs together would change what the page says. */
  it("separates blocks", () => {
    expect(textOf(page("<p>A</p><p>B</p>"))).toBe("A B");
  });

  it.each([
    ["divs", "<div>A</div><div>B</div>"],
    ["list items", "<ul><li>A</li><li>B</li></ul>"],
    ["table cells", "<table><tr><td>A</td><td>B</td></tr></table>"],
    ["headings and paragraphs", "<h1>A</h1><p>B</p>"],
  ])("separates %s", (_name, markup) => {
    expect(textOf(page(markup))).toBe("A B");
  });

  it("treats a line break as a separator", () => {
    expect(textOf(page("<p>A<br>B</p>"))).toBe("A B");
  });

  it("does not split a sentence around an image", () => {
    expect(textOf(page('<p><span>A</span><img src="x.png"><span>B</span></p>'))).toBe(
      "AB",
    );
  });
});

/**
 * **Elements this has never heard of flow inline.**
 *
 * The opposite rule looks safer and is not. Treating an unknown element as a
 * boundary means that rewriting a component — the same words, wrapped in a
 * different tag — moves the text and moves the digest, and a reader is told a
 * page changed when nothing they can see is different. Enough of those and the
 * watcher is noise.
 *
 * It is also what the platform does: an element nobody has styled renders
 * `display: inline`. Nothing here reads CSS, so the alternative would be a
 * guess about styling rather than a conservative default.
 */
describe("elements the extractor does not know", () => {
  const withSpans = page("<span>A</span><span>B</span>");
  const withCustomElements = page(
    "<custom-a>A</custom-a><custom-b>B</custom-b>",
  );

  it("joins text across known inline elements", () => {
    expect(textOf(withSpans)).toBe("AB");
  });

  it("joins text across custom elements in the same way", () => {
    expect(textOf(withCustomElements)).toBe("AB");
  });

  /** The regression this rule exists for: markup-only edits are not changes. */
  it("reports no change when only the tags were swapped", () => {
    expect(hashOf(withCustomElements)).toBe(hashOf(withSpans));
  });

  it("still reports a change when the words inside them differ", () => {
    expect(hashOf(page("<custom-a>B</custom-a>"))).not.toBe(
      hashOf(page("<custom-a>A</custom-a>")),
    );
  });

  it.each([
    ["a hyphenated custom element", "<my-widget>A</my-widget><my-widget>B</my-widget>"],
    ["an unknown element without a hyphen", "<widget>A</widget><widget>B</widget>"],
    ["a nested custom element", "<outer-x><inner-y>A</inner-y></outer-x><span>B</span>"],
  ])("does not insert a boundary for %s", (_name, markup) => {
    expect(textOf(page(markup))).toBe("AB");
  });

  /** Known blocks keep their boundaries — the rule narrowed, it did not vanish. */
  it.each([
    ["paragraphs", "<p>A</p><p>B</p>"],
    ["divs", "<div>A</div><div>B</div>"],
    ["list items", "<ul><li>A</li><li>B</li></ul>"],
    ["table cells", "<table><tr><td>A</td><td>B</td></tr></table>"],
    ["sections", "<section>A</section><section>B</section>"],
  ])("still separates %s", (_name, markup) => {
    expect(textOf(page(markup))).toBe("A B");
  });

  /** A block wrapped in a custom element is still a block. */
  it("keeps the boundary of a known block nested inside a custom element", () => {
    expect(textOf(page("<custom-a><p>A</p><p>B</p></custom-a>"))).toBe("A B");
  });
});

describe("what must move the text", () => {
  it.each([
    ["a date", "2026/08/17", "2026/08/18"],
    ["a time", "09:00", "09:30"],
    ["a price", "¥9,800", "¥10,800"],
    ["a number", "残り 3 席", "残り 2 席"],
    ["a phone number", "03-1234-5678", "03-1234-5679"],
    ["Japanese text", "採用情報", "採用終了"],
    ["an emoji", "在庫あり ✅", "在庫なし ❌"],
    ["letter case", "Sold Out", "sold out"],
    ["punctuation", "Yes.", "Yes!"],
    ["a displayed URL", "https://a.example/x", "https://a.example/y"],
  ])("reports %s changing", (_name, before, after) => {
    expect(hashOf(page(`<p>${after}</p>`))).not.toBe(
      hashOf(page(`<p>${before}</p>`)),
    );
  });

  /**
   * **Nothing here guesses whether a date is a deploy stamp or a deadline.**
   * Stripping "dynamic-looking" values is how a watcher stops noticing the
   * thing it was pointed at.
   */
  it("keeps a timestamp that could have been dismissed as noise", () => {
    expect(textOf(page("<p>Updated 2026-08-17 09:00</p>"))).toBe(
      "Updated 2026-08-17 09:00",
    );
  });
});

describe("a page with nothing to read", () => {
  it.each([
    ["an empty body", page("")],
    ["only a script", "<html><script>const a = 1;</script></html>"],
    ["only whitespace", page("   \n\t  ")],
    ["nothing at all", ""],
  ])("normalizes %s to an empty string", (_name, html) => {
    expect(textOf(html)).toBe("");
  });

  /**
   * **Empty is a baseline, not a failure.** A page that serves nothing today
   * and something tomorrow has changed, and that only works if today was
   * recorded.
   */
  it("still produces a digest, and the same one every time", () => {
    const first = normalizeWebsiteContent(page(""), "text/html");
    const second = normalizeWebsiteContent(
      "<html><script>x</script></html>",
      "text/html",
    );

    expect(first.normalizedContent).toBe("");
    expect(first.contentHash).toBe(second.contentHash);
    expect(first.contentHash).toMatch(/^[0-9a-f]{64}$/);
  });

  it("reports text appearing on a page that had none", () => {
    expect(hashOf(page("<p>Now there is something</p>"))).not.toBe(
      hashOf(page("")),
    );
  });
});

describe("markup a browser would have to guess at", () => {
  it.each([
    ["unclosed tags", "<html><body><p>One<p>Two</body></html>"],
    ["a stray close tag", "<html><body><p>One</span></p></body></html>"],
    ["missing html and body", "<p>One</p><p>Two</p>"],
    ["badly nested tags", "<html><body><b><i>One</b></i></body></html>"],
    ["an unclosed attribute quote", '<html><body><p class="a>One</p></body></html>'],
    ["text before any tag", "One<html><body><p>Two</p></body></html>"],
  ])("recovers from %s rather than failing", (_name, html) => {
    expect(() => normalizeWebsiteContent(html, "text/html")).not.toThrow();
  });

  it("still finds the words in badly nested markup", () => {
    expect(textOf("<html><body><b><i>One</b></i></body></html>")).toBe("One");
  });

  it("still separates paragraphs that were never closed", () => {
    expect(textOf("<html><body><p>One<p>Two</body></html>")).toBe("One Two");
  });
});

describe("responses that are not documents", () => {
  function kindOf(contentType: string | undefined): string {
    try {
      normalizeWebsiteContent("<p>hi</p>", contentType);
    } catch (error) {
      return isWatcherError(error)
        ? (error as WatcherError).kind
        : "not-a-watcher-error";
    }

    return "normalized";
  }

  it.each(["application/json", "application/pdf", "text/plain", "image/png"])(
    "refuses %s",
    (contentType) => {
      expect(kindOf(contentType)).toBe("unsupported-content-type");
    },
  );

  it("refuses a response that did not say what it was", () => {
    expect(kindOf(undefined)).toBe("unsupported-content-type");
  });

  it("accepts XHTML", () => {
    expect(kindOf("application/xhtml+xml")).toBe("normalized");
  });
});

describe("normalizeWhitespace on its own", () => {
  it("is idempotent, so normalizing twice changes nothing", () => {
    const once = normalizeWhitespace(" A \n\t B  ");
    expect(normalizeWhitespace(once)).toBe(once);
    expect(once).toBe("A B");
  });

  it("does not fold case", () => {
    expect(normalizeWhitespace("Sold Out")).not.toBe(
      normalizeWhitespace("sold out"),
    );
  });

  /**
   * Zero-width characters are not spaces. Removing them would be editing the
   * text rather than tidying it, and the rule here is to tidy only.
   *
   * The argument below is `A`, U+200B ZERO WIDTH SPACE, `B` — invisible in this
   * file, which is the reason it is spelled out here.
   */
  it("leaves a zero-width space alone", () => {
    expect(normalizeWhitespace("A​B")).toBe("A​B");
  });

  /**
   * **No Unicode normalisation.** The two arguments below are the composed
   * U+00E9 and the decomposed `e` + U+0301 COMBINING ACUTE ACCENT: identical on
   * screen, different strings. Folding them would make a real edit compare
   * equal, which is the direction this must never fail in.
   */
  it("does not normalize Unicode", () => {
    expect(normalizeWhitespace("é")).not.toBe(normalizeWhitespace("é"));
  });
});
